<?php
/**
 * Created by PhpStorm.
 * User: Alejandro Suarez
 * Date: 07/06/14
 * Time: 10:14
 */

require_once(__ROOT__ . '\lib\medoo.min.php');

class Application
{
    private static $_database = null;
    private static $_application = null;

    private function __construct()
    {
    }

    public static function getApplication()
    {
        if (is_null(self::$_application)) {
            self::$_application = array(
                'name' => 'FP2Req',
                'fullName' => 'From Process to Requirement',
                'database' => self::getDataBase()
            );
            return self::$_application;
        }
    }

    public static function getDataBase()
    {
        if (is_null(self::$_database)) {
            self::$_database = new medoo([
                // required
                'database_type' => 'mysql',
                'database_name' => 'fp2req_db',
                'server' => 'localhost',
                'username' => 'root',
                'password' => ''
            ]);
        }
        return self::$_database;
    }

    public static function generateJSModels()
    {

    }

    public static function loader($path)
    {
        if (is_null($path)) {
            $path = dirname(__FILE__);
        }

        $dir = new DirectoryIterator($path);
        /** @var DirectoryIterator $fileinfo */
        foreach ($dir as $fileinfo) {
            if (!$fileinfo->isDot()) {

                if (self::endsWith($fileinfo->getFilename(), '.php')) {
                    require_once($fileinfo->getPathname());
                }
                if ($fileinfo->isDir()) {
                    self::loader($fileinfo->getPathname());
                }
                if ($fileinfo->getFilename() == 'ModelJS.js') {
                    unlink($fileinfo->getPathname());
                }
            }
        }

    }

    static function clearDirectory($directory)
    {
         //   unlink($directory);
        $dir = new DirectoryIterator($directory);
        foreach ($dir as $file) {
            if (!$file->isDot()) {
                unlink($file->getPathname());
            }
        }

    }

    static function createModelsJS($path)
    {   $class = "/**GENERATED BY CORE**/\n";
        echo '<script src="/layout/.core/C.View/Model.js"></script>';
        echo '<script src="/layout/view//ModelJS.js"></script>';
        $dir = new DirectoryIterator($path . "\\model");
        foreach ($dir as $fileinfo) {
            if (!$fileinfo->isDot() && !$fileinfo->isDir()) {
                $name = $fileinfo->getFilename();
                if (self::endsWith($name, '.php')) {
                    $name = str_replace('.php', "", $name);
                    $data = $name::getStructure();
                    $class .=  "function ".$name."(){\n".
                        "\tthis.data = ".json_encode($data)."\n}\n"
                        .$name.".prototype = new Model();\n\n";
                }
            }
        }
        $path = __APPLICATION__."/view/ModelJS.js";
        $fichier = fopen($path, "w");
        if (!fwrite($fichier, $class)) {
            echo "Impossible de créer le fichier";
        }
        fclose($fichier);

    }

    static function endsWith($haystack, $needle)
    {
        return $needle === "" || substr($haystack, -strlen($needle)) === $needle;
    }

} 