/**GENERATED BY CORE**/
function Analyst(){
	this.data = {"id":"","email":"","password":"","name":"","lastname":"","type":"","_createdAt":""}
}
Analyst.prototype = new Model();

function Project(){
	this.data = {"id":"","idAnalyst":"","name":"","description":"","_createdAt":""}
}
Project.prototype = new Model();

